PORT=27015
SV_LAN=0
MAP="de_dust2"
MAXPLAYERS=16
CS_HOSTNAME="Encore63"
CS_PASSWORD="loda"
RCON_PASSWORD="loda"
STEAMCMD_DIR=$(echo $HOME/steam_commander)
HLDS_DIR=$(echo $HOME/HLDS)
MODS_DIR=$(echo $(pwd)/mods)